'use client'

import { motion } from 'framer-motion'

const LINKS = [
  { label: 'Web Dev', target: 'level-services' },
  { label: 'AI Video', target: 'level-services' },
  { label: 'AI Design', target: 'level-services' },
  { label: 'Work', target: 'level-work' },
  { label: 'Process', target: 'level-process' },
  { label: 'Contact', target: 'level-contact' },
]

export function Footer() {
  return (
    <footer
      className="relative w-full overflow-hidden border-t border-white/5 bg-background pt-20 pb-10"
      aria-label="End Credits"
    >
      {/* Particle/gradient bookend matching hero */}
      <div
        className="pointer-events-none absolute inset-0 z-0 opacity-60"
        style={{
          background:
            'radial-gradient(60% 60% at 50% 0%, oklch(0.15 0.05 290 / 40%) 0%, transparent 70%)',
        }}
      />
      <div className="pointer-events-none absolute inset-0 z-0 bg-grid opacity-20 mask-fade-b" />

      <div className="relative z-10 mx-auto max-w-7xl px-6">
        {/* Top: brand + nav */}
        <div className="grid grid-cols-1 gap-10 md:grid-cols-3">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, amount: 0.5 }}
            transition={{ duration: 0.6 }}
          >
            <div className="flex items-center gap-3">
              <div className="relative h-9 w-9">
                <div className="absolute inset-0 rounded-sm border border-white/30" />
                <div className="absolute inset-1 rounded-sm bg-gradient-to-br from-violet to-cyan" />
                <div className="absolute inset-0 flex items-center justify-center font-display text-xs font-bold text-white">
                  R
                </div>
              </div>
              <div className="flex flex-col leading-none">
                <span className="font-display text-base font-semibold tracking-wide">
                  RAJNESH UPADHYAY
                </span>
                <span className="text-[10px] uppercase tracking-[0.3em] text-muted-foreground">
                  Web · AI Video · AI Design
                </span>
              </div>
            </div>
            <p className="mt-4 max-w-xs text-sm text-muted-foreground">
              Building cinematic, scroll-driven 3D web experiences and synthetic visual
              content from a single creator-owned studio.
            </p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, amount: 0.5 }}
            transition={{ duration: 0.6, delay: 0.1 }}
          >
            <div className="text-[10px] uppercase tracking-[0.4em] text-muted-foreground">
              Navigate
            </div>
            <ul className="mt-4 flex flex-wrap gap-x-6 gap-y-2">
              {LINKS.map((l) => (
                <li key={l.label}>
                  <button
                    onClick={() =>
                      document.getElementById(l.target)?.scrollIntoView({ behavior: 'smooth' })
                    }
                    data-cursor="jump"
                    className="text-sm text-foreground/80 transition-colors hover:text-gradient-accent"
                  >
                    {l.label}
                  </button>
                </li>
              ))}
            </ul>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, amount: 0.5 }}
            transition={{ duration: 0.6, delay: 0.2 }}
          >
            <div className="text-[10px] uppercase tracking-[0.4em] text-muted-foreground">
              Status
            </div>
            <div className="mt-4 flex items-center gap-2">
              <span className="h-2 w-2 animate-pulse rounded-full bg-green-400" />
              <span className="text-sm text-foreground/80">Open for new quests</span>
            </div>
            <p className="mt-2 text-xs text-muted-foreground">
              Avg response time under 24h · IST timezone
            </p>
          </motion.div>
        </div>

        {/* End credits roll line */}
        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true, amount: 0.5 }}
          transition={{ duration: 1 }}
          className="mt-16 flex flex-col items-center justify-center gap-3 border-t border-white/5 pt-8 text-center"
        >
          <div className="text-[10px] uppercase tracking-[0.4em] text-muted-foreground">
            End Credits
          </div>
          <div className="font-display text-sm text-foreground/60">
            Designed, engineered, and AI-generated by Rajnesh Upadhyay.
          </div>
          <div className="text-[10px] uppercase tracking-[0.3em] text-muted-foreground/60">
            Next.js · React Three Fiber · GSAP · Tailwind · Custom GLSL · © {new Date().getFullYear()}
          </div>
        </motion.div>
      </div>
    </footer>
  )
}
